### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by heikostark** [mhahsler/seriation#10]
> R

R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-mageia-linux-gnu (64-bit)

> install.packages("seriation")

Warnung: Abhängigkeit ‘caTools’ nicht verfügbar
installiere auch Abhängigkeit ‘gplots’

versuche URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/gplots_3.0.1.2.tar.gz'
Content type 'application/octet-stream' length 638102 bytes (623 KB)
downloaded 623 KB

versuche URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/seriation_1.2-8.tar.gz'
Content type 'application/octet-stream' length 898343 bytes (877 KB)
downloaded 877 KB

ERROR: dependency ‘caTools’ is not available for package ‘gplots’
* removing ‘/usr/lib64/R/library/gplots’
ERROR: dependency ‘gplots’ is not available for package ‘seriation’
* removing ‘/usr/lib64/R/library/seriation’

Die heruntergeladenen Quellpakete sind in 
        ‘/tmp/RtmplhSKyj/downloaded_packages’
Aktualisiere HTML Index der Pakete in '.Library'
Making 'packages.html' ... fertig
Warnmeldungen:
1: In install.packages("seriation") :
  Installation des Pakets ‘gplots’ hatte Exit-Status ungleich 0
2: In install.packages("seriation") :
  Installation des Pakets ‘seriation’ hatte Exit-Status ungleich 0

---

> update.packages(checkBuild=TRUE, ask=FALSE)

Doesn't help.

**Comment by mhahsler** [comment]
Hmm. Looks like the culprit is package caTools. Can you install caTools using the following?
    
install.packlages("caTools")

**Comment by heikostark** [comment]
> install.packages("caTools")

Warnmeldung:
Paket ‘caTools’ ist nicht verfügbar (for R version 3.5.3) 
(Package 'caTools' is not available)

**Comment by mhahsler** [comment]
It looks like the current version of caTools requires R version 1.6.0 (see https://cran.r-project.org/web/packages/caTools/index.html). Your options are to install a current version of R or an older version of caTools (see link above).
