### ISSUE TITLE
register_*() functions no longer exported

### ISSUE THREAD

**Issue by thomasp85** [mhahsler/seriation#15]
It seems the different variants of `register_*()` are no longer being exported (except for `register_GA()`). However, the documentation still links to its use. Have they been removed in error, or are they no longer needed?

tidygraph is being flagged by CRAN because it relies on `register_DendSer()` so if it has been removed in error I hope it can be fixed quickly so I don't have to momentarily remove seriation as a dependency

**Comment by mhahsler** [comment]
Thank you for the bug report. A fixed version is now on GitHub. I will send a new version to CRAN ASAP.

Regards,
-Michael

**Comment by mhahsler** [comment]
The fixed version is on its way to CRAN.

**Comment by thomasp85** [comment]
Thanks for the quick action
