### ISSUE TITLE
Coordinate of sample in Hamiltonian path

### ISSUE THREAD

**Issue by NicolasHipp** [mhahsler/seriation#2]
Hi everyone, 

First, I would like to say that your package is really nice, I'm a biologist who try to understand how statistic and bio-informatics works together so sorry if I ask some basic questions.
I have a time course analysis of RNAsequencing from naive toward differentiated cells, and I would like to class my sample by the differentiation path. I have 8 time-points with 3 replicates by time point. I sorted a count_matrix for all the genes, and extract the matrix distance for them:

df<-dist(t(Count_matrix)
I choose the "OLO" method to order my sample : 
res <- dissplot(d, method = "OLO",
                options = list(main = "Seriation OLO method"))
I understand that the Hamiltonian path is the minimum distance path that can relies all my sample. So I would like to extract the Hamiltonian length:
criterion(d, method =  "Path_length") 
Path_length 
   4635.551

And know, I would like to take the position of my sample on this path but I cannot find the way to do that.
Is there a possibility to do that? 

Thank a lot,
Nicolas

**Comment by mhahsler** [comment]
Create the order first:

`o <- seriate(d, method = "OLO")`

Now you can use it for different things:

```
dissplot(d, o)
criterion(d, o, method = "Path_length")
get_order(o)
```

**Comment by NicolasHipp** [comment]
Thanks for the help, It helped :)
