### ISSUE TITLE
S3 conflict with package "sf"

### ISSUE THREAD

**Issue by cysouw** [mhahsler/seriation#21]
As far as I have been able to track it down, there seems to be an S3 conflict between this package and the package `sf`.

```
Registered S3 methods overwritten by 'proxy':
  method               from    
  print.registry_field registry
  print.registry_entry registry
```

I don't know how many packages import both `seriation` and `sf`, but my package `qlcVisualize` does this, so this warning pops up every time it is loaded.

Everything still works, but it would be nice if this conflict could be resolved.

**Comment by mhahsler** [comment]
Hi,

There exists a name clash between the proxy and registry packages. It is not serious because both packages provide the same code. I have notified the maintainer.
