### ISSUE TITLE
PAST seriation method implemented in R

### ISSUE THREAD

**Issue by benmarwick** [mhahsler/seriation#23]
The [PAST software](https://www.nhm.uio.no/english/research/resources/past/) is a free closed source program that is popular in paleontology and archaeology and uses a seriation algorithm from [Brower and Kile (1988)](https://www.idunn.no/doi/full/10.1111/j.1502-3931.1988.tb01756.x) which was also documented in [Burroughs & Brower (1982)](https://doi.org/10.1016/0098-3004(82)90017-6). 

There was no implementation of this in R until recently when @kbvernon wrote one here: https://github.com/kbvernon/brower-kile-1988, which is excellent and finally provides an open source option for this seriation method.

I think it would be really great if it could be incorporated into this package, as this package is the go-to for all things seriation. I'm hoping to start a discussion to let @mhahsler know of this new implementation, and encourage @kbvernon to make a PR here.

**Comment by kbvernon** [comment]
Thanks! And yes, I'm happy to submit a PR if this is something the authors would like to include.

**Comment by mhahsler** [comment]
Thanks for letting me know. A PR would be very welcome.

**Comment by mhahsler** [comment]
Completed!
