### ISSUE TITLE
seration to return a dendrogram object after reodering

### ISSUE THREAD

**Issue by crazyhottommy** [mhahsler/seriation#3]
Hi,

Many thanks for this package, I am playing around with it.
I usually use ComplexHeatmap for making heatmaps.

The following code works fine.
```r
library(ComplexHeatmap)
library(seriation)

data("iris")
x <- as.matrix(iris[-5])

seri_order<- c(seriate(dist(x, method = "euclidean"), method = "OLO_ward"),
  seriate(dist(t(x), method = "euclidean"), method = "OLO_ward"))

Heatmap( x[get_order(seri_order, 1), get_order(seri_order, 2)], cluster_rows = F, cluster_columns = F, show_row_names = F)
```
but I want to show the dendrograms in the heatmap as well, I know in the package `hmap` function can do it, but I want to stick with Complexheatmap.

I need `seriation` to return back a dendrogram object (reordered with OLO) and pass it to Complexheatmap

something like below so the reordered dendrogram can be shown.
```r

rowdend<- seriate(dist(x, method = "euclidean"), method = "OLO_ward")
col_dend <- seriate(dist(t(x), method = "euclidean"), method = "OLO_ward")

Heatmap( x,  cluster_rows = row_dend,
        cluster_columns = col_dend)
```

Thanks!
Tommy

**Comment by crazyhottommy** [comment]
it seems this will do the work.

```r
as.dendrogram(seri_order[[2]])
```

**Comment by mhahsler** [comment]
Glad this is solved.
