### ISSUE TITLE
Unable to use "reorder.hclust" function

### ISSUE THREAD

**Issue by Tomer-Tsaban** [mhahsler/seriation#5]
Hi, 
for some reason (unknown to me) I can't use the "reorder.hclust" function.
I installed seriation package correctly, but there is no option as "reorder" at all. other functions do appear and I can use them (seriate for example). 

I tried reinstalling the package, and even R itself (including Rstudio) but nothing changes.
any ideas?

* in this picture you can see that there is no "reorder.hclust" option in the package functions.
![seriation](https://user-images.githubusercontent.com/32357066/44306371-2ff7f000-a396-11e8-9f30-a21a1ccd234e.png)

thanks!

**Comment by talgalili** [comment]
The seriate_dendrogram (from the dendextend package) tries to offer a simpler wrapper, see if that helps you:
https://rdrr.io/cran/dendextend/man/seriate_dendrogram.html

**Comment by mhahsler** [comment]
reorder is a generic function so `reorder.hclust` is not exported. Try `?reorder` and you should see that `seriation` offers a reorder method for dendrograms. Alternatively, you can use `seriation:::`  (three colons) to see what is inside the package. Hope this helps.
