### ISSUE TITLE
fill color in bertinplot has not effect

### ISSUE THREAD

**Issue by Derek-Jones** [mhahsler/seriation#6]
In the code:

```
bertinplot(fmat, fser,  options=list(panel=panel.squares, spacing=0,
                                                    gp_panels=gpar(col="green", fill="red")))
```

The `col` setting results in green lines, but the `fill` option has no effect (i.e., the fill color remains black)

Looking at the code, the variable `hl` does not appears to get its value from the `highlight` variable.

**Comment by mhahsler** [comment]
highlight and shading overwrites the fill argument that you specify. I have updated the code so fill now replaces the color correctly. You now can also specify a matrix with color values for all the panels in highlight.

**Comment by mhahsler** [comment]
Please check out the version on GitHub. The changes will be part of the next release.
