### ISSUE TITLE
Redundant write in loop

### ISSUE THREAD

**Issue by RichardKav** [mhahsler/seriation#8]
In the file bea.f there are two loops on line 38 and 180. It writes the first row/column to the reordered matrix. The following lines are contained inside the loop but shouldn't be, given subsequent calls make no change to the ifin and ib or jb variables.

>      ifin(istart) = 0
>      ib(nplace) = istart

The loop should only encompass the assignment to b(1,j) and b(i,1) respectively.

**Comment by mhahsler** [comment]
Thanks for letting me know. The improved code is now available on Github and will be part of the next release.

-Michael
