### ISSUE TITLE
Save output of pimage (to plot along with other plots)

### ISSUE THREAD

**Issue by psyguy** [mhahsler/seriation#9]
Hi,

I'm using `pimage()` and `seriate()` to visualize adjacency matrices of my networks and they are great. However, I need to put `pimage` plots next to each other (and other plots) using, for instance, `par()` or `screen()`.

Do you have an idea how to do this? Or, could you modify the function so that it does the job?
Thanks.

**Comment by mhahsler** [comment]
Hi,

`pimage()` uses `grid` and that is why `par()` and `screen()` do not work. In the manual page (`?pimage`) is an example of how to put several plots on a page using `viewport()`.

**Comment by psyguy** [comment]
I wonder how have I missed the examples there. Thanks!
